---
DOWN: 
  drop_table: 
    - users
UP: 
  create_table: 
    users: 
      username: 
        type: string
        default: false
        length: 255
        - not_null
      password: 
        type: string
        default: false
        length: 40
        - not_null
      user_type: 
        type: string
        default: 'visitor'
        length: 10
        index: true
        - not_null
      status: 
        type: string
        default: 'active'
        length: 10
        index: true
        - not_null
      full_name: 
        type: string
        default: false
        length: 255
        - not_null
      email_address: 
        type: string
        default: false
        length: 127
        index: true
        - not_null
      address: 
        type: text
        default: false
        length: 
        - is_null
      phone_number: 
        type: string
        default: false
        length: 16
        - is_null
