---
DOWN: 
  drop_table: 
    - addresses
UP: 
  create_table: 
    addresses: 
      user_id: 
        type: integer
        default: false
        length: 11
        index: true
        - not_null
      address: 
        type: text
        default: false
        length: 
        - is_null
      is_default: 
        type: integer
        default: false
        length: 1
        index: true
        - not_null
