---
DOWN: 
  drop_table: 
    - stores
UP: 
  create_table: 
    stores: 
      user_id: 
        type: integer
        default: false
        length: 11
        index: true
        - not_null
      store_name: 
        type: string
        default: false
        length: 255
        - not_null
      store_address: 
        type: text
        default: false
        length: 
        - is_null
      latitude: 
        type: float
        default: 0.000000
        length: 9,6
        - not_null
      longitude: 
        type: float
        default: 0.000000
        length: 9,6
        - not_null
