---
DOWN: 
  drop_table: 
    - contacts
UP: 
  create_table: 
    contacts: 
      name: 
        type: string
        default: false
        length: 255
        - not_null
      email_address: 
        type: string
        default: false
        length: 127
        - not_null
      message: 
        type: text
        default: false
        length: 
        - is_null
      ip_address: 
        type: int
        default: false
        length: 20
        - not_null
