---
UP:
  add_fields:
    users:
      forgot_password_code:
        type: string
        length: 40
      forgot_password_expire:
        type: datetime
DOWN:
  drop_fields:
    users:
      forgot_password_code: forgot_password_code
      forgot_password_expire: forgot_password_expire
