---
UP:
  add_fields:
    stores:
      city:
        type: string
        length: 255
      country:
        type: string
        length: 255
      zipcode:
        type: string
        length: 5
      store_phone:
        type: string
        length: 16
      store_email:
        type: string
        length: 127
DOWN:
  drop_fields:
    stores:
      city: city
      country: country
      zipcode: zipcode
      store_phone: store_phone
      store_email: store_email
