---
DOWN: 
  drop_table: 
    - categories
UP: 
  create_table: 
    categories:
      name: 
        type: string
        length: 255
        - not_null
      parent_id:
        type: int
        length: 11
        - not_null
      category_image:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
