---
DOWN: 
  drop_table: 
    - products
UP: 
  create_table: 
    products:
      name: 
        type: string
        length: 255
        - not_null
      category_id:
        type: int
        length: 11
        - not_null
      description:
        type: string
        length: 255
        - not_null
      price:
        type: float
        length: 18,2
        - not_null
      sku:
        type: string
        length: 20
      color:
        type: string
        length: 20
      size:
        type: string
        length: 20
      product_image:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
