---
DOWN: 
  drop_table: 
    - product_images
UP: 
  create_table: 
    product_images:
      product_id:
        type: int
        length: 11
        - not_null
      image_filename:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
