---
UP:
  add_fields:
    products:
      read_count:
        type: int
        length: 11
      last_view_time:
        type: datetime
      is_recommended:
        type: int
        length: 1
DOWN:
  drop_fields:
    products:
      read_count: read_count
      last_view_time: last_view_time
      is_recommended: is_recommended
