---
UP:
  add_fields:
    users:
      activation_code:
        type: string
        length: 40
  alter_fields:
    users:
      user_type:
        type: string
        default: 'buyer'
        length: 10
        index: true
        - not_null
  query:
    - "UPDATE users SET user_type='buyer' WHERE user_type='visitor'"

DOWN:
  drop_fields:
    users:
      - activation_code
  alter_fields:
    users:
      user_type:
        type: string
        default: 'visitor'
        length: 10
        index: true
        - not_null
  query:
    - "UPDATE users SET user_type='visitor' WHERE user_type='buyer'"
