---
DOWN: 
  drop_table: 
    - carts
UP: 
  create_table: 
    carts: 
      user_id: 
        type: integer
        default: false
        length: 11
        - not_null
      status: 
        type: string
        default: false
        length: 20
        - not_null
