---
DOWN: 
  drop_table: 
    - item_images
UP: 
  create_table:
    item_images:
      item_id:
        type: int
        length: 11
        - not_null
      image_file:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
