---
UP:
  add_fields:
    carts:
      invoice_number:
        type: string
        length: 50
      invoice_date:
        type: datetime
      shipping_address:
        type: text
DOWN:
  drop_fields:
    carts:
      invoice_number: invoice_number
      invoice_date: invoice_date
      shipping_address: shipping_address
