---
DOWN: 
  drop_field:
    cart_items:
      item_id: item_id
  add_field:
    cart_items:
      product_id:
        type: int
        length: 11
        - not_null
UP: 
  drop_field:
    cart_items:
      product_id: product_id
  add_field:
    cart_items:
      item_id:
        type: int
        length: 11
        - not_null            
 