---
DOWN: 
  drop_table: 
    - settings
UP: 
  create_table: 
    settings:
      setting_key:
        type: string
        length: 255
        primary: true
        - not_null
      setting_group:
        type: string
        length: 255
        index: true
      setting_type:
        type: string
        length: 255
      setting_label:
        type: string
        length: 255
      setting_value:
        type: text
      setting_options:
        type: string
        length: 255
      setting_weight:
        type: integer
        length: 11
      - no_id
  query:
    - "INSERT INTO `settings` (`setting_key`, `setting_group`, `setting_type`, `setting_label`, `setting_value`, `setting_weight`, `modified`, `created`) VALUES ('active_template', 'Homescreen', 'text', 'Active Template', 'horizontal', 1, NOW(), NOW())"
