---
DOWN: 
  drop_table: 
    - website_images
UP: 
  create_table:
    website_images:
      image_for:
        type: string
        length: 255
        - not_null
      thumbsize:
        type: string
        length: 255
        default: 'normal'
        - not_null
      image_file:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
