---
DOWN: 
  drop_table: 
    - galleries
UP: 
  create_table:
    galleries:
      album_id:
        type: int
        length: 11
      gallery_image:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255