---
UP:
  add_fields:
    m_item_type:
      original_category_id:
        type: string
        length: 1
  query:
    - "UPDATE `m_item_type` SET `original_category_id` = `category_id` "
    - "ALTER TABLE `m_item_type` CHANGE `category_id` `category_id` INT(10) "
    - "UPDATE `m_item_type` SET `category_id` = 5 WHERE original_category_id IN (2,4,5,6,7,8,9) "
    - "UPDATE `m_item_type` SET `category_id` = 4 WHERE original_category_id IN (3) "
DOWN:
  query:
    - "ALTER TABLE `m_item_type` CHANGE `category_id` `category_id` VARCHAR(1) "
    - "UPDATE `m_item_type` SET `category_id` = `original_category_id` "
  drop_fields:
    m_item_type:
      - original_category_id
