---
DOWN: 
  drop_table: 
    - polls
UP: 
  create_table: 
    polls: 
      question: 
        type: string
        default: false
        length: 500
        - not_null
      question_en: 
        type: string
        default: false
        length: 500
        - not_null        
      is_published:
        type: int
        length: 1
      end_date: 
        type: date
        default: false
        length:
        - not_null
      type: 
        type: integer
        default: 1
        length: 1
        - not_null

