---
DOWN: 
  drop_table: 
    - user_answers
UP: 
  create_table: 
    user_answers: 
      poll_id: 
        type: integer
        default: false
        length: 
        - not_null
      user_id: 
        type: integer
        default: 0
        length: 
        - is_null
      choice: 
        type: text
        default: false
        length: 200
        - not_null
      ip: 
        type: string
        default: false
        length: 30
        - not_null
      browser_type: 
        type: integer
        default: false
        length: 1
        - not_null
