---
UP:
  add_fields:
    m_item:
      total_stock:
        type: integer
        length: 11
      actual_stock:
        type: integer
        length: 11
      booked_stock:
        type: integer
        length: 11
      release_stock:
        type: integer
        length: 11
      reject_stock:
        type: integer
        length: 11
  create_table:
    stock_history:
      user_id:
        type: integer
        default: 0
        length: 11
        index: true
        - not_null
      status:
        type: string
        default: 'add'
        length: 20
        - not_null
      stock_num:
        type: int
        default: 0
        length: 11
        - not_null
DOWN:
  drop_table:
    - stock_history
  drop_fields:
    m_item:
      - reject_stock
      - release_stock
      - booked_stock
      - actual_stock
      - total_stock
