---
UP:
  add_fields:
    stock_history:
      item_id:
        type: integer
        default: 0
        length: 11
        index: true
        - not_null
  query:
    - "ALTER TABLE `stock_history` ADD INDEX (`item_id`) "
DOWN:
  drop_fields:
    stock_history:
      - item_id
