---
DOWN:
  drop_table:
    - item_recomends
UP:
  create_table:
    item_recomends:
      item_id:
        type: integer
        default: false
        length: 11
        index: true
        - not_null
      recomend_id:
        type: integer
        default: false
        length: 11
        index: true
        - not_null
