---
UP:
  add_fields:
    galleries:
      description:
        type: string
        length: 100
      photographer:
        type: string
        length: 100
DOWN:
  drop_fields:
    galleries:
      description: description
      photographer: photographer
