---
UP:
  add_fields:
    tags:
      tag_image:
        type: string
        length: 255
      dir:
        type: string
        length: 255
      filesize:
        type: int
        length: 11
      realname:
        type: string
        length: 255
      mimetype:
        type: string
        length: 255
DOWN:
  drop_fields:
    tags:
      tag_image: tag_image
      dir: dir
      filesize: filesize
      realname: realname
      mimetype: mimetype
