---
UP:
  add_fields:
    carts:
      postal_service:
        type: string
        length: 100
      tracking_number:
        type: string
        length: 50
      shipping_costs:
        type: float
        default: 0.0
        length: 18,2
        - not_null
      total_plus_shipping:
        type: float
        default: 0.0
        length: 18,2
        - not_null
DOWN:
  drop_fields:
    carts:
      postal_service: postal_service
      tracking_number: tracking_number
      shipping_costs: shipping_costs
      total_plus_shipping: total_plus_shipping
